export interface FieldDefinition {
  name: string;
  labelEn: string;
  labelHi: string;
  type: "text" | "number" | "date";
  placeholderEn: string;
  placeholderHi: string;
  required: boolean;
}

export interface DocumentTypeInfo {
  id: string;
  titleEn: string;
  titleHi: string;
  descEn: string;
  descHi: string;
  fields: FieldDefinition[];
}

export const DOCUMENT_TYPES: DocumentTypeInfo[] = [
  {
    id: "vendor",
    titleEn: "Vendor Agreement",
    titleHi: "विक्रेता अनुबंध",
    descEn: "Agreement between a buyer and supplier for goods or services",
    descHi: "खरीदार और आपूर्तिकर्ता के बीच सामान या सेवाओं के लिए अनुबंध",
    fields: [
      {
        name: "buyerName",
        labelEn: "Party A (Buyer) Full Name",
        labelHi: "पार्टी A (खरीदार) का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Ramesh Kumar",
        placeholderHi: "जैसे: रमेश कुमार",
        required: true,
      },
      {
        name: "buyerBusiness",
        labelEn: "Party A Business Name",
        labelHi: "पार्टी A व्यवसाय का नाम",
        type: "text",
        placeholderEn: "e.g. Kumar Kirana & Sons",
        placeholderHi: "जैसे: कुमार किराना एंड संस",
        required: true,
      },
      {
        name: "buyerAddress",
        labelEn: "Party A Address",
        labelHi: "पार्टी A का पता",
        type: "text",
        placeholderEn: "e.g. Shop 42, Gali No. 3, Chandni Chowk, Delhi",
        placeholderHi: "जैसे: दुकान 42, गली नंबर 3, चांदनी चौक, दिल्ली",
        required: true,
      },
      {
        name: "vendorName",
        labelEn: "Party B (Vendor) Full Name",
        labelHi: "पार्टी B (विक्रेता) का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Suresh Singh",
        placeholderHi: "जैसे: सुरेश सिंह",
        required: true,
      },
      {
        name: "vendorBusiness",
        labelEn: "Party B Business Name",
        labelHi: "पार्टी B व्यवसाय का नाम",
        type: "text",
        placeholderEn: "e.g. Singh Wholesale Foods",
        placeholderHi: "जैसे: सिंह थोक खाद्य पदार्थ",
        required: true,
      },
      {
        name: "vendorAddress",
        labelEn: "Party B Address",
        labelHi: "पार्टी B का पता",
        type: "text",
        placeholderEn: "e.g. Plot 15, Industrial Area, Okhla, Delhi",
        placeholderHi: "जैसे: प्लॉट 15, औद्योगिक क्षेत्र, ओखला, दिल्ली",
        required: true,
      },
      {
        name: "goodsServices",
        labelEn: "Goods/Services to be Supplied",
        labelHi: "आपूर्ति की जाने वाली वस्तु या सेवा",
        type: "text",
        placeholderEn: "e.g. Supply of premium basmati rice and spices monthly",
        placeholderHi: "जैसे: प्रीमियम बासमती चावल और मसालों की मासिक आपूर्ति",
        required: true,
      },
      {
        name: "contractValue",
        labelEn: "Total Contract Value (₹)",
        labelHi: "कुल अनुबंध मूल्य",
        type: "text",
        placeholderEn: "e.g. 1,50,000",
        placeholderHi: "जैसे: 1,50,000",
        required: true,
      },
      {
        name: "paymentTerms",
        labelEn: "Payment Terms",
        labelHi: "भुगतान शर्तें",
        type: "text",
        placeholderEn: "e.g. Net 30 days after invoice and delivery",
        placeholderHi: "जैसे: चालान और डिलीवरी के बाद 30 दिन",
        required: true,
      },
      {
        name: "deliveryTimeline",
        labelEn: "Delivery Timeline",
        labelHi: "डिलीवरी समयरेखा",
        type: "text",
        placeholderEn: "e.g. By the 5th working day of each calendar month",
        placeholderHi: "जैसे: प्रत्येक कैलेंडर माह के 5वें कार्य दिवस तक",
        required: true,
      },
      {
        name: "startDate",
        labelEn: "Contract Start Date",
        labelHi: "अनुबंध प्रारंभ तिथि",
        type: "date",
        placeholderEn: "",
        placeholderHi: "",
        required: true,
      },
      {
        name: "endDate",
        labelEn: "Contract End Date",
        labelHi: "अनुबंध समाप्ति तिथि",
        type: "date",
        placeholderEn: "",
        placeholderHi: "",
        required: true,
      },
      {
        name: "penaltyDelay",
        labelEn: "Penalty for Delay (₹ or %)",
        labelHi: "देरी के लिए जुर्माना",
        type: "text",
        placeholderEn: "e.g. ₹500 per day or 1% of shipment value per week",
        placeholderHi: "जैसे: ₹500 प्रति दिन या 1% प्रति सप्ताह",
        required: true,
      },
      {
        name: "governingState",
        labelEn: "Governing State (Jurisdiction)",
        labelHi: "शासी राज्य",
        type: "text",
        placeholderEn: "e.g. Delhi",
        placeholderHi: "जैसे: दिल्ली",
        required: true,
      },
      {
        name: "placeSigning",
        labelEn: "Place of Signing",
        labelHi: "हस्ताक्षर का स्थान",
        type: "text",
        placeholderEn: "e.g. New Delhi, India",
        placeholderHi: "जैसे: नई दिल्ली, भारत",
        required: true,
      },
    ],
  },
  {
    id: "nda",
    titleEn: "Non-Disclosure Agreement",
    titleHi: "गोपनीयता अनुबंध",
    descEn: "Keeps business information confidential between two parties",
    descHi: "दो पक्षों के बीच व्यावसायिक जानकारी को गोपनीय रखता है",
    fields: [
      {
        name: "disclosingParty",
        labelEn: "Disclosing Party Full Name",
        labelHi: "जानकारी देने वाले का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Anita Sharma",
        placeholderHi: "जैसे: अनीता शर्मा",
        required: true,
      },
      {
        name: "disclosingBusiness",
        labelEn: "Disclosing Party Business",
        labelHi: "जानकारी देने वाले का व्यवसाय",
        type: "text",
        placeholderEn: "e.g. Sharma Biotech Labs",
        placeholderHi: "जैसे: शर्मा बायोटेक लैब्स",
        required: true,
      },
      {
        name: "receivingParty",
        labelEn: "Receiving Party Full Name",
        labelHi: "जानकारी प्राप्त करने वाले का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Vinay Verma",
        placeholderHi: "जैसे: विनय वर्मा",
        required: true,
      },
      {
        name: "receivingBusiness",
        labelEn: "Receiving Party Business",
        labelHi: "जानकारी प्राप्त करने वाले का व्यवसाय",
        type: "text",
        placeholderEn: "e.g. Verma Retail Franchises",
        placeholderHi: "जैसे: वर्मा रिटेल फ्रैंचाइज़ी",
        required: true,
      },
      {
        name: "purpose",
        labelEn: "Purpose of Sharing Information",
        labelHi: "जानकारी साझा करने का उद्देश्य",
        type: "text",
        placeholderEn: "e.g. Evaluating business partnership and franchise setup",
        placeholderHi: "जैसे: व्यावसायिक साझेदारी और फ्रैंचाइज़ी का मूल्यांकन",
        required: true,
      },
      {
        name: "confidentialInfo",
        labelEn: "What information is confidential?",
        labelHi: "कौन सी जानकारी गोपनीय है?",
        type: "text",
        placeholderEn: "e.g. Proprietary recipes, billing software, and customer lists",
        placeholderHi: "जैसे: मालिकाना रेसिपी, बिलिंग सॉफ़्टवेयर और ग्राहकों की सूची",
        required: true,
      },
      {
        name: "duration",
        labelEn: "Duration of Confidentiality (years)",
        labelHi: "गोपनीयता की अवधि",
        type: "text",
        placeholderEn: "e.g. 3 years or 5 years",
        placeholderHi: "जैसे: 3 वर्ष या 5 वर्ष",
        required: true,
      },
      {
        name: "penaltyBreach",
        labelEn: "Penalty for Breach (₹)",
        labelHi: "उल्लंघन के लिए जुर्माना",
        type: "text",
        placeholderEn: "e.g. ₹1,00,000 plus legal expenses incurred",
        placeholderHi: "जैसे: ₹1,00,000 प्लस कानूनी खर्च",
        required: true,
      },
      {
        name: "governingState",
        labelEn: "Governing State",
        labelHi: "शासी राज्य",
        type: "text",
        placeholderEn: "e.g. Maharashtra",
        placeholderHi: "जैसे: महाराष्ट्र",
        required: true,
      },
      {
        name: "agreementDate",
        labelEn: "Date of Agreement",
        labelHi: "अनुबंध की तिथि",
        type: "date",
        placeholderEn: "",
        placeholderHi: "",
        required: true,
      },
    ],
  },
  {
    id: "rental",
    titleEn: "Shop Rental Agreement",
    titleHi: "दुकान किराया अनुबंध",
    descEn: "Lease agreement between shop owner and tenant",
    descHi: "दुकान मालिक और किरायेदार के बीच किराया अनुबंध",
    fields: [
      {
        name: "landlordName",
        labelEn: "Landlord Full Name",
        labelHi: "मकान मालिक का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Harish Prasad",
        placeholderHi: "जैसे: हरीश प्रसाद",
        required: true,
      },
      {
        name: "landlordAddress",
        labelEn: "Landlord Address",
        labelHi: "मकान मालिक का पता",
        type: "text",
        placeholderEn: "e.g. H.No 105, Sector 15, Noida, Uttar Pradesh",
        placeholderHi: "जैसे: मकान नंबर 105, सेक्टर 15, नोएडा",
        required: true,
      },
      {
        name: "tenantName",
        labelEn: "Tenant Full Name",
        labelHi: "किरायेदार का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Deepak Kumar Shah",
        placeholderHi: "जैसे: दीपक कुमार शाह",
        required: true,
      },
      {
        name: "tenantAddress",
        labelEn: "Tenant Address",
        labelHi: "किरायेदार का पता",
        type: "text",
        placeholderEn: "e.g. Flat B-4, Green Valley Apartments, Noida",
        placeholderHi: "जैसे: फ्लैट बी-4, ग्रीन वैली अपार्टमेंट्स, नोएडा",
        required: true,
      },
      {
        name: "shopAddress",
        labelEn: "Shop Address",
        labelHi: "दुकान का पता",
        type: "text",
        placeholderEn: "e.g. Shop No. 5, Sector 18 Market, Noida, U.P.",
        placeholderHi: "जैसे: दुकान नंबर 5, सेक्टर 18 मार्केट, नोएडा",
        required: true,
      },
      {
        name: "shopArea",
        labelEn: "Shop Area (sq ft)",
        labelHi: "दुकान का क्षेत्रफल",
        type: "text",
        placeholderEn: "e.g. 350 sq ft",
        placeholderHi: "जैसे: 350 वर्ग फुट",
        required: true,
      },
      {
        name: "monthlyRent",
        labelEn: "Monthly Rent (₹)",
        labelHi: "मासिक किराया",
        type: "text",
        placeholderEn: "e.g. 25,000",
        placeholderHi: "जैसे: 25,000",
        required: true,
      },
      {
        name: "securityDeposit",
        labelEn: "Security Deposit (₹)",
        labelHi: "सिक्योरिटी डिपॉज़िट",
        type: "text",
        placeholderEn: "e.g. 75,000",
        placeholderHi: "जैसे: 75,000",
        required: true,
      },
      {
        name: "leaseStartDate",
        labelEn: "Lease Start Date",
        labelHi: "किराया प्रारंभ तिथि",
        type: "date",
        placeholderEn: "",
        placeholderHi: "",
        required: true,
      },
      {
        name: "leaseDuration",
        labelEn: "Lease Duration (months)",
        labelHi: "किराया अवधि (महीने)",
        type: "text",
        placeholderEn: "e.g. 11 months",
        placeholderHi: "जैसे: 11 महीने",
        required: true,
      },
      {
        name: "rentEscalation",
        labelEn: "Rent Escalation",
        labelHi: "किराया वृद्धि (% प्रति वर्ष)",
        type: "text",
        placeholderEn: "e.g. 5% or 10% per year",
        placeholderHi: "जैसे: 5% या 10% प्रति वर्ष",
        required: true,
      },
      {
        name: "permittedUse",
        labelEn: "Permitted Use of Shop",
        labelHi: "दुकान का अनुमत उपयोग",
        type: "text",
        placeholderEn: "e.g. Grocery store / Kirana business only",
        placeholderHi: "जैसे: किराना स्टोर / किराना व्यवसाय",
        required: true,
      },
      {
        name: "noticePeriod",
        labelEn: "Notice Period for Termination (days)",
        labelHi: "समाप्ति के लिए नोटिस अवधि",
        type: "text",
        placeholderEn: "e.g. 30 days or 60 days",
        placeholderHi: "जैसे: 30 दिन या 60 दिन",
        required: true,
      },
      {
        name: "governingState",
        labelEn: "Governing State",
        labelHi: "शासी राज्य",
        type: "text",
        placeholderEn: "e.g. Uttar Pradesh",
        placeholderHi: "जैसे: उत्तर प्रदेश",
        required: true,
      },
    ],
  },
  {
    id: "service",
    titleEn: "Service Agreement",
    titleHi: "सेवा अनुबंध",
    descEn: "Contract for providing a specific service over a period",
    descHi: "एक निश्चित अवधि में विशिष्ट सेवा प्रदान करने का अनुबंध",
    fields: [
      {
        name: "providerName",
        labelEn: "Service Provider Full Name",
        labelHi: "सेवा प्रदाता का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Manoj Joshi",
        placeholderHi: "जैसे: मनोज जोशी",
        required: true,
      },
      {
        name: "providerBusiness",
        labelEn: "Service Provider Business",
        labelHi: "सेवा प्रदाता का व्यवसाय",
        type: "text",
        placeholderEn: "e.g. Joshi IT Solutions & Consulting",
        placeholderHi: "जैसे: जोशी आईटी सॉल्यूशंस",
        required: true,
      },
      {
        name: "clientName",
        labelEn: "Client Full Name",
        labelHi: "ग्राहक का पूरा नाम",
        type: "text",
        placeholderEn: "e.g. Rajendra Gupta",
        placeholderHi: "जैसे: राजेंद्र गुप्ता",
        required: true,
      },
      {
        name: "clientBusiness",
        labelEn: "Client Business",
        labelHi: "ग्राहक का व्यवसाय",
        type: "text",
        placeholderEn: "e.g. Gupta Cloth Emporium",
        placeholderHi: "जैसे: गुप्ता क्लॉथ एम्पोरियम",
        required: true,
      },
      {
        name: "servicesDescription",
        labelEn: "Description of Services",
        labelHi: "सेवाओं का विवरण",
        type: "text",
        placeholderEn: "e.g. Managing inventory software, updates, and cloud backups",
        placeholderHi: "जैसे: इन्वेंट्री सॉफ्टवेयर प्रबंधन, अपडेट और बैकअप",
        required: true,
      },
      {
        name: "serviceStartDate",
        labelEn: "Service Start Date",
        labelHi: "सेवा प्रारंभ तिथि",
        type: "date",
        placeholderEn: "",
        placeholderHi: "",
        required: true,
      },
      {
        name: "serviceEndDate",
        labelEn: "Service End Date",
        labelHi: "सेवा समाप्ति तिथि",
        type: "date",
        placeholderEn: "",
        placeholderHi: "",
        required: true,
      },
      {
        name: "totalFee",
        labelEn: "Total Fee (₹)",
        labelHi: "कुल शुल्क",
        type: "text",
        placeholderEn: "e.g. 45,000 total or 5,000 monthly",
        placeholderHi: "जैसे: 45,000 कुल या 5,000 मासिक",
        required: true,
      },
      {
        name: "paymentSchedule",
        labelEn: "Payment Schedule",
        labelHi: "भुगतान कार्यक्रम",
        type: "text",
        placeholderEn: "e.g. 50% advance, 50% upon successful software delivery",
        placeholderHi: "जैसे: 50% अग्रिम, 50% सॉफ्टवेयर डिलीवरी पर",
        required: true,
      },
      {
        name: "penaltyNonPerformance",
        labelEn: "Penalty for Non-Performance",
        labelHi: "अनुपालन न होने पर जुर्माना",
        type: "text",
        placeholderEn: "e.g. Direct refund of advance plus 10% penalty charge",
        placeholderHi: "जैसे: अग्रिम राशि की सीधी वापसी और 10% अतिरिक्त जुर्माना",
        required: true,
      },
      {
        name: "terminationNotice",
        labelEn: "Termination Notice Period (days)",
        labelHi: "समाप्ति नोटिस अवधि",
        type: "text",
        placeholderEn: "e.g. 15 days or 30 days",
        placeholderHi: "जैसे: 15 दिन या 30 दिन",
        required: true,
      },
      {
        name: "governingState",
        labelEn: "Governing State",
        labelHi: "शासी राज्य",
        type: "text",
        placeholderEn: "e.g. Gujarat",
        placeholderHi: "जैसे: गुजरात",
        required: true,
      },
    ],
  },
];
